#include <iostream>
#include <vector>
#include <stack>
using namespace std;

// Daily Coding Problem: Problem #50 [Easy] - 15/11/25
//
// This problem was asked by Microsoft.
// Suppose an arithmetic expression is given as a binary tree.
// Each leaf is an integer and each internal node is one of '+', '−', '∗', or '/'.
//
// Given the root to such a tree, write a function to evaluate it.
// For example, given the following tree:
//
//     *
//    / \
//   +    +
//  / \  / \
// 3  2  4  5
//
// You should return 45, as it is (3 + 2) * (4 + 5).

struct TreeNode {
    char val;
    TreeNode* left;
    TreeNode* right;
    TreeNode(char val) : val(val) {}
    TreeNode(char val, TreeNode* left, TreeNode* right) : val(val), left(left), right(right) {}
};

class Solution {
public:
    int evaluateFromTree(TreeNode* root) {
        if (!root) return 0;

        if (!root->left && !root->right) {
            return root->val - '0';
        }

        int leftVal = evaluateFromTree(root->left);
        int rightVal = evaluateFromTree(root->right);

        switch (root->val) {
            case '+': return leftVal + rightVal;
            case '-': return leftVal - rightVal;
            case '*': return leftVal * rightVal;
            case '/': return leftVal / rightVal;
        }
        return 0;
    }
};

int main() {
    // Daily Coding Problem: Problem #50 [Easy] - 15/11/25
    Solution solution;

    // Test cases generated by Claude

    // Test Case 1: Original Example
    // Tree:     *
    //          / \
    //         +   +
    //        / \ / \
    //       3 2 4 5
    // Expression: (3 + 2) * (4 + 5) = 5 * 9 = 45
    TreeNode* test1 = new TreeNode('*',
        new TreeNode('+', new TreeNode('3'), new TreeNode('2')),
        new TreeNode('+', new TreeNode('4'), new TreeNode('5'))
    );

    // Test Case 2: Simple Addition
    // Tree:  +
    //       / \
    //      7   8
    // Expression: 7 + 8 = 15
    TreeNode* test2 = new TreeNode('+', new TreeNode('7'), new TreeNode('8'));

    // Test Case 3: Single Node
    // Tree: 9
    // Expression: 9
    TreeNode* test3 = new TreeNode('9');

    // Test Case 4: Subtraction with Nested Operations
    // Tree:     -
    //          / \
    //         *   +
    //        / \ / \
    //       6 3 2 4
    // Expression: (6 * 3) - (2 + 4) = 18 - 6 = 12
    TreeNode* test4 = new TreeNode('-',
        new TreeNode('*', new TreeNode('6'), new TreeNode('3')),
        new TreeNode('+', new TreeNode('2'), new TreeNode('4'))
    );

    // Test Case 5: Division
    // Tree:     /
    //          / \
    //         *   -
    //        / \ / \
    //       8 3 7 1
    // Expression: (8 * 3) / (7 - 1) = 24 / 6 = 4
    TreeNode* test5 = new TreeNode('/',
        new TreeNode('*', new TreeNode('8'), new TreeNode('3')),
        new TreeNode('-', new TreeNode('7'), new TreeNode('1'))
    );

    // Test Case 6: Left-Heavy Tree
    // Tree:       +
    //            / \
    //           *   5
    //          / \
    //         +   4
    //        / \
    //       2   3
    // Expression: ((2 + 3) * 4) + 5 = (5 * 4) + 5 = 25
    TreeNode* test6 = new TreeNode('+',
        new TreeNode('*',
            new TreeNode('+', new TreeNode('2'), new TreeNode('3')),
            new TreeNode('4')
        ),
        new TreeNode('5')
    );

    // Test Case 7: Right-Heavy Tree
    // Tree:   -
    //        / \
    //       9   *
    //          / \
    //         +   2
    //        / \
    //       1   3
    // Expression: 9 - ((1 + 3) * 2) = 9 - (4 * 2) = 1
    TreeNode* test7 = new TreeNode('-',
        new TreeNode('9'),
        new TreeNode('*',
            new TreeNode('+', new TreeNode('1'), new TreeNode('3')),
            new TreeNode('2')
        )
    );

    // Test Case 8: Complex Expression with Zero Result
    // Tree:       *
    //            / \
    //           +   -
    //          / \ / \
    //         /  2 8  *
    //        / \     / \
    //       6   3   4   2
    // Expression: ((6/3) + 2) * (8 - (4*2)) = (2 + 2) * (8 - 8) = 4 * 0 = 0
    TreeNode* test8 = new TreeNode('*',
        new TreeNode('+',
            new TreeNode('/', new TreeNode('6'), new TreeNode('3')),
            new TreeNode('2')
        ),
        new TreeNode('-',
            new TreeNode('8'),
            new TreeNode('*', new TreeNode('4'), new TreeNode('2'))
        )
    );

    // Run all tests
    cout << "Test 1 (Original): " << solution.evaluateFromTree(test1) << " (Expected: 45)" << endl;
    cout << "Test 2 (Simple): " << solution.evaluateFromTree(test2) << " (Expected: 15)" << endl;
    cout << "Test 3 (Single): " << solution.evaluateFromTree(test3) << " (Expected: 9)" << endl;
    cout << "Test 4 (Subtraction): " << solution.evaluateFromTree(test4) << " (Expected: 12)" << endl;
    cout << "Test 5 (Division): " << solution.evaluateFromTree(test5) << " (Expected: 4)" << endl;
    cout << "Test 6 (Left-Heavy): " << solution.evaluateFromTree(test6) << " (Expected: 25)" << endl;
    cout << "Test 7 (Right-Heavy): " << solution.evaluateFromTree(test7) << " (Expected: 1)" << endl;
    cout << "Test 8 (Complex): " << solution.evaluateFromTree(test8) << " (Expected: 0)" << endl;

    return 0;
}
